### ISSUE TITLE
No shapefile output (bigdata branch)

### ISSUE THREAD

**Issue by kawikakanaka** [tannerjt/AGStoShapefile#31]
My cmd output is showing that a shapefile was created, but I'm not seeing it in my output folder.  There are only the json and geojson files.
![image](https://cloud.githubusercontent.com/assets/26749488/25765540/61a5cb7a-31a2-11e7-8483-bca3128f0920.png)

**Comment by tannerjt** [comment]
Thanks @kawikakanaka - I have removed the comment from the bigdata branch stating a shapefile is being created.  The modifications to this branch actually only create the Esri JSON and GeoJSON files.  I usually use QGIS to merge the geojson files into one.

**Comment by kawikakanaka** [comment]
Oh ok thanks @tannerjt !  By the way...this tool is awesome!  I use it all the time : )

**Comment by tannerjt** [comment]
Thank You @kawikakanaka !! :smile:  I'm glad it is useful.  There are some other really good libraries I have come across lately too if this one has issues.  I saw a presentation from @gdherbert recently called [DataPillager](https://github.com/gdherbert/DataPillager) that was really good.  @openaddresses also has a library called [pyesridump](https://github.com/openaddresses/pyesridump) that has come in useful.  I use this one all the time too since it is relatively simple and easy to tweak for unexpected issues!
